// Code generated by girgen. DO NOT EDIT.

package gtksource

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
	"github.com/diamondburned/gotk4/pkg/gtk/v4"
)

// #include <stdlib.h>
// #include <gtksourceview/gtksource.h>
import "C"

// StyleSchemePreviewClass: instance of this type is always passed by reference.
type StyleSchemePreviewClass struct {
	*styleSchemePreviewClass
}

// styleSchemePreviewClass is the struct that's finalized.
type styleSchemePreviewClass struct {
	native *C.GtkSourceStyleSchemePreviewClass
}

func (s *StyleSchemePreviewClass) ParentClass() *gtk.WidgetClass {
	valptr := &s.native.parent_class
	var _v *gtk.WidgetClass // out
	_v = (*gtk.WidgetClass)(gextras.NewStructNative(unsafe.Pointer(valptr)))
	return _v
}
