// Code generated by girgen. DO NOT EDIT.

package gtksource

import (
	"github.com/diamondburned/gotk4/pkg/core/gbox"
)

// #include <stdlib.h>
// #include <gtksourceview/gtksource.h>
import "C"

//export _gotk4_gtksource5_SchedulerCallback
func _gotk4_gtksource5_SchedulerCallback(arg1 C.gint64, arg2 C.gpointer) (cret C.gboolean) {
	var fn SchedulerCallback
	{
		v := gbox.Get(uintptr(arg2))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(SchedulerCallback)
	}

	var _deadline int64 // out

	_deadline = int64(arg1)

	ok := fn(_deadline)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}
