// Code generated by girgen. DO NOT EDIT.

package gtksource

// #include <stdlib.h>
// #include <gtksourceview/gtksource.h>
import "C"

// AnnotationsClass: instance of this type is always passed by reference.
type AnnotationsClass struct {
	*annotationsClass
}

// annotationsClass is the struct that's finalized.
type annotationsClass struct {
	native *C.GtkSourceAnnotationsClass
}
