// Code generated by girgen. DO NOT EDIT.

package gtksource

import (
	"fmt"
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/atk"
	"github.com/diamondburned/gotk4/pkg/cairo"
	"github.com/diamondburned/gotk4/pkg/core/gextras"
	externglib "github.com/diamondburned/gotk4/pkg/core/glib"
	"github.com/diamondburned/gotk4/pkg/gdk/v3"
	"github.com/diamondburned/gotk4/pkg/gtk/v3"
)

// #include <stdlib.h>
// #include <glib-object.h>
// #include <gtksourceview/gtksource.h>
import "C"

func init() {
	externglib.RegisterGValueMarshalers([]externglib.TypeMarshaler{
		{T: externglib.Type(C.gtk_source_gutter_renderer_alignment_mode_get_type()), F: marshalGutterRendererAlignmentMode},
		{T: externglib.Type(C.gtk_source_gutter_renderer_get_type()), F: marshalGutterRendererer},
	})
}

// GutterRendererAlignmentMode: alignment mode of the renderer, when a cell
// spans multiple lines (due to text wrapping).
type GutterRendererAlignmentMode C.gint

const (
	// SourceGutterRendererAlignmentModeCell: full cell.
	SourceGutterRendererAlignmentModeCell GutterRendererAlignmentMode = iota
	// SourceGutterRendererAlignmentModeFirst: first line.
	SourceGutterRendererAlignmentModeFirst
	// SourceGutterRendererAlignmentModeLast: last line.
	SourceGutterRendererAlignmentModeLast
)

func marshalGutterRendererAlignmentMode(p uintptr) (interface{}, error) {
	return GutterRendererAlignmentMode(externglib.ValueFromNative(unsafe.Pointer(p)).Enum()), nil
}

// String returns the name in string for GutterRendererAlignmentMode.
func (g GutterRendererAlignmentMode) String() string {
	switch g {
	case SourceGutterRendererAlignmentModeCell:
		return "Cell"
	case SourceGutterRendererAlignmentModeFirst:
		return "First"
	case SourceGutterRendererAlignmentModeLast:
		return "Last"
	default:
		return fmt.Sprintf("GutterRendererAlignmentMode(%d)", g)
	}
}

// GutterRendererOverrider contains methods that are overridable.
//
// As of right now, interface overriding and subclassing is not supported
// yet, so the interface currently has no use.
type GutterRendererOverrider interface {
	// Activate emits the SourceGutterRenderer::activate signal of the renderer.
	// This is called from SourceGutter and should never have to be called
	// manually.
	//
	// The function takes the following parameters:
	//
	//    - iter at the start of the line where the renderer is activated.
	//    - area of the cell area where the renderer is activated.
	//    - event that triggered the activation.
	//
	Activate(iter *gtk.TextIter, area *gdk.Rectangle, event *gdk.Event)
	// Begin: called when drawing a region begins. The region to be drawn is
	// indicated by start and end. The purpose is to allow the implementation to
	// precompute some state before the draw method is called for each cell.
	//
	// The function takes the following parameters:
	//
	//    - cr: #cairo_t.
	//    - backgroundArea: Rectangle.
	//    - cellArea: Rectangle.
	//    - start: TextIter.
	//    - end: TextIter.
	//
	Begin(cr *cairo.Context, backgroundArea, cellArea *gdk.Rectangle, start, end *gtk.TextIter)
	// ChangeBuffer: this is called when the text buffer changes for renderer.
	//
	// The function takes the following parameters:
	//
	//    - oldBuffer (optional): old TextBuffer.
	//
	ChangeBuffer(oldBuffer *gtk.TextBuffer)
	// ChangeView: this is called when the text view changes for renderer.
	//
	// The function takes the following parameters:
	//
	//    - oldView (optional): old TextView.
	//
	ChangeView(oldView *gtk.TextView)
	// Draw: main renderering method. Implementations should implement this
	// method to draw onto the cairo context. The background_area indicates the
	// total area of the cell to be drawn. The cell_area indicates the area
	// where content can be drawn (text, images, etc).
	//
	// The background_area is the cell_area plus the padding on each side (two
	// times the SourceGutterRenderer:xpad horizontally and two times the
	// SourceGutterRenderer:ypad vertically, so that the cell_area is centered
	// inside background_area).
	//
	// The state argument indicates the current state of the renderer and should
	// be taken into account to properly draw the different possible states
	// (cursor, prelit, selected) if appropriate.
	//
	// The function takes the following parameters:
	//
	//    - cr: cairo render context.
	//    - backgroundArea indicating the total area to be drawn.
	//    - cellArea indicating the area to draw content.
	//    - start: TextIter.
	//    - end: TextIter.
	//    - state: SourceGutterRendererState.
	//
	Draw(cr *cairo.Context, backgroundArea, cellArea *gdk.Rectangle, start, end *gtk.TextIter, state GutterRendererState)
	// End: called when drawing a region of lines has ended.
	End()
	// QueryActivatable: get whether the renderer is activatable at the location
	// in event. This is called from SourceGutter to determine whether a
	// renderer is activatable using the mouse pointer.
	//
	// The function takes the following parameters:
	//
	//    - iter at the start of the line to be activated.
	//    - area of the cell area to be activated.
	//    - event that triggered the query.
	//
	// The function returns the following values:
	//
	//    - ok: TRUE if the renderer can be activated, FALSE otherwise.
	//
	QueryActivatable(iter *gtk.TextIter, area *gdk.Rectangle, event *gdk.Event) bool
	// QueryData: emit the SourceGutterRenderer::query-data signal. This
	// function is called to query for data just before rendering a cell. This
	// is called from the SourceGutter. Implementations can override the default
	// signal handler or can connect a signal handler externally to the
	// SourceGutterRenderer::query-data signal.
	//
	// The function takes the following parameters:
	//
	//    - start: TextIter.
	//    - end: TextIter.
	//    - state: SourceGutterRendererState.
	//
	QueryData(start, end *gtk.TextIter, state GutterRendererState)
	// QueryTooltip emits the SourceGutterRenderer::query-tooltip signal. This
	// function is called from SourceGutter. Implementations can override the
	// default signal handler or can connect to the signal externally.
	//
	// The function takes the following parameters:
	//
	//    - iter: TextIter.
	//    - area: Rectangle.
	//    - x position of the tooltip.
	//    - y position of the tooltip.
	//    - tooltip: Tooltip.
	//
	// The function returns the following values:
	//
	//    - ok: TRUE if the tooltip has been set, FALSE otherwise.
	//
	QueryTooltip(iter *gtk.TextIter, area *gdk.Rectangle, x, y int, tooltip *gtk.Tooltip) bool
	// QueueDraw emits the SourceGutterRenderer::queue-draw signal of the
	// renderer. Call this from an implementation to inform that the renderer
	// has changed such that it needs to redraw.
	QueueDraw()
}

type GutterRenderer struct {
	_ [0]func() // equal guard
	externglib.InitiallyUnowned
}

var ()

// GutterRendererer describes types inherited from class GutterRenderer.
//
// To get the original type, the caller must assert this to an interface or
// another type.
type GutterRendererer interface {
	externglib.Objector
	baseGutterRenderer() *GutterRenderer
}

var _ GutterRendererer = (*GutterRenderer)(nil)

func wrapGutterRenderer(obj *externglib.Object) *GutterRenderer {
	return &GutterRenderer{
		InitiallyUnowned: externglib.InitiallyUnowned{
			Object: obj,
		},
	}
}

func marshalGutterRendererer(p uintptr) (interface{}, error) {
	return wrapGutterRenderer(externglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

func (renderer *GutterRenderer) baseGutterRenderer() *GutterRenderer {
	return renderer
}

// BaseGutterRenderer returns the underlying base object.
func BaseGutterRenderer(obj GutterRendererer) *GutterRenderer {
	return obj.baseGutterRenderer()
}

// ConnectActivate signal is emitted when the renderer is activated.
func (renderer *GutterRenderer) ConnectActivate(f func(iter *gtk.TextIter, area *gdk.Rectangle, event *gdk.Event)) externglib.SignalHandle {
	return renderer.Connect("activate", f)
}

// ConnectQueryActivatable signal is emitted when the renderer can possibly be
// activated.
func (renderer *GutterRenderer) ConnectQueryActivatable(f func(iter *gtk.TextIter, area *gdk.Rectangle, event *gdk.Event) bool) externglib.SignalHandle {
	return renderer.Connect("query-activatable", f)
}

// ConnectQueryData signal is emitted when the renderer needs to be filled with
// data just before a cell is drawn. This can be used by general renderer
// implementations to allow render data to be filled in externally.
func (renderer *GutterRenderer) ConnectQueryData(f func(start, end *gtk.TextIter, state GutterRendererState)) externglib.SignalHandle {
	return renderer.Connect("query-data", f)
}

// ConnectQueryTooltip signal is emitted when the renderer can show a tooltip.
func (renderer *GutterRenderer) ConnectQueryTooltip(f func(iter *gtk.TextIter, area *gdk.Rectangle, x, y int, tooltip gtk.Tooltip) bool) externglib.SignalHandle {
	return renderer.Connect("query-tooltip", f)
}

// ConnectQueueDraw signal is emitted when the renderer needs to be redrawn. Use
// gtk_source_gutter_renderer_queue_draw() to emit this signal from an
// implementation of the SourceGutterRenderer interface.
func (renderer *GutterRenderer) ConnectQueueDraw(f func()) externglib.SignalHandle {
	return renderer.Connect("queue-draw", f)
}

// Activate emits the SourceGutterRenderer::activate signal of the renderer.
// This is called from SourceGutter and should never have to be called manually.
//
// The function takes the following parameters:
//
//    - iter at the start of the line where the renderer is activated.
//    - area of the cell area where the renderer is activated.
//    - event that triggered the activation.
//
func (renderer *GutterRenderer) Activate(iter *gtk.TextIter, area *gdk.Rectangle, event *gdk.Event) {
	var _arg0 *C.GtkSourceGutterRenderer // out
	var _arg1 *C.GtkTextIter             // out
	var _arg2 *C.GdkRectangle            // out
	var _arg3 *C.GdkEvent                // out

	_arg0 = (*C.GtkSourceGutterRenderer)(unsafe.Pointer(renderer.Native()))
	_arg1 = (*C.GtkTextIter)(gextras.StructNative(unsafe.Pointer(iter)))
	_arg2 = (*C.GdkRectangle)(gextras.StructNative(unsafe.Pointer(area)))
	_arg3 = (*C.GdkEvent)(gextras.StructNative(unsafe.Pointer(event)))

	C.gtk_source_gutter_renderer_activate(_arg0, _arg1, _arg2, _arg3)
	runtime.KeepAlive(renderer)
	runtime.KeepAlive(iter)
	runtime.KeepAlive(area)
	runtime.KeepAlive(event)
}

// Begin: called when drawing a region begins. The region to be drawn is
// indicated by start and end. The purpose is to allow the implementation to
// precompute some state before the draw method is called for each cell.
//
// The function takes the following parameters:
//
//    - cr: #cairo_t.
//    - backgroundArea: Rectangle.
//    - cellArea: Rectangle.
//    - start: TextIter.
//    - end: TextIter.
//
func (renderer *GutterRenderer) Begin(cr *cairo.Context, backgroundArea, cellArea *gdk.Rectangle, start, end *gtk.TextIter) {
	var _arg0 *C.GtkSourceGutterRenderer // out
	var _arg1 *C.cairo_t                 // out
	var _arg2 *C.GdkRectangle            // out
	var _arg3 *C.GdkRectangle            // out
	var _arg4 *C.GtkTextIter             // out
	var _arg5 *C.GtkTextIter             // out

	_arg0 = (*C.GtkSourceGutterRenderer)(unsafe.Pointer(renderer.Native()))
	_arg1 = (*C.cairo_t)(unsafe.Pointer(cr.Native()))
	_arg2 = (*C.GdkRectangle)(gextras.StructNative(unsafe.Pointer(backgroundArea)))
	_arg3 = (*C.GdkRectangle)(gextras.StructNative(unsafe.Pointer(cellArea)))
	_arg4 = (*C.GtkTextIter)(gextras.StructNative(unsafe.Pointer(start)))
	_arg5 = (*C.GtkTextIter)(gextras.StructNative(unsafe.Pointer(end)))

	C.gtk_source_gutter_renderer_begin(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5)
	runtime.KeepAlive(renderer)
	runtime.KeepAlive(cr)
	runtime.KeepAlive(backgroundArea)
	runtime.KeepAlive(cellArea)
	runtime.KeepAlive(start)
	runtime.KeepAlive(end)
}

// Draw: main renderering method. Implementations should implement this method
// to draw onto the cairo context. The background_area indicates the total area
// of the cell to be drawn. The cell_area indicates the area where content can
// be drawn (text, images, etc).
//
// The background_area is the cell_area plus the padding on each side (two times
// the SourceGutterRenderer:xpad horizontally and two times the
// SourceGutterRenderer:ypad vertically, so that the cell_area is centered
// inside background_area).
//
// The state argument indicates the current state of the renderer and should be
// taken into account to properly draw the different possible states (cursor,
// prelit, selected) if appropriate.
//
// The function takes the following parameters:
//
//    - cr: cairo render context.
//    - backgroundArea indicating the total area to be drawn.
//    - cellArea indicating the area to draw content.
//    - start: TextIter.
//    - end: TextIter.
//    - state: SourceGutterRendererState.
//
func (renderer *GutterRenderer) Draw(cr *cairo.Context, backgroundArea, cellArea *gdk.Rectangle, start, end *gtk.TextIter, state GutterRendererState) {
	var _arg0 *C.GtkSourceGutterRenderer     // out
	var _arg1 *C.cairo_t                     // out
	var _arg2 *C.GdkRectangle                // out
	var _arg3 *C.GdkRectangle                // out
	var _arg4 *C.GtkTextIter                 // out
	var _arg5 *C.GtkTextIter                 // out
	var _arg6 C.GtkSourceGutterRendererState // out

	_arg0 = (*C.GtkSourceGutterRenderer)(unsafe.Pointer(renderer.Native()))
	_arg1 = (*C.cairo_t)(unsafe.Pointer(cr.Native()))
	_arg2 = (*C.GdkRectangle)(gextras.StructNative(unsafe.Pointer(backgroundArea)))
	_arg3 = (*C.GdkRectangle)(gextras.StructNative(unsafe.Pointer(cellArea)))
	_arg4 = (*C.GtkTextIter)(gextras.StructNative(unsafe.Pointer(start)))
	_arg5 = (*C.GtkTextIter)(gextras.StructNative(unsafe.Pointer(end)))
	_arg6 = C.GtkSourceGutterRendererState(state)

	C.gtk_source_gutter_renderer_draw(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5, _arg6)
	runtime.KeepAlive(renderer)
	runtime.KeepAlive(cr)
	runtime.KeepAlive(backgroundArea)
	runtime.KeepAlive(cellArea)
	runtime.KeepAlive(start)
	runtime.KeepAlive(end)
	runtime.KeepAlive(state)
}

// End: called when drawing a region of lines has ended.
func (renderer *GutterRenderer) End() {
	var _arg0 *C.GtkSourceGutterRenderer // out

	_arg0 = (*C.GtkSourceGutterRenderer)(unsafe.Pointer(renderer.Native()))

	C.gtk_source_gutter_renderer_end(_arg0)
	runtime.KeepAlive(renderer)
}

// Alignment: get the x-alignment and y-alignment of the gutter renderer.
//
// The function returns the following values:
//
//    - xalign (optional): return location for the x-alignment, or NULL to
//      ignore.
//    - yalign (optional): return location for the y-alignment, or NULL to
//      ignore.
//
func (renderer *GutterRenderer) Alignment() (xalign float32, yalign float32) {
	var _arg0 *C.GtkSourceGutterRenderer // out
	var _arg1 C.gfloat                   // in
	var _arg2 C.gfloat                   // in

	_arg0 = (*C.GtkSourceGutterRenderer)(unsafe.Pointer(renderer.Native()))

	C.gtk_source_gutter_renderer_get_alignment(_arg0, &_arg1, &_arg2)
	runtime.KeepAlive(renderer)

	var _xalign float32 // out
	var _yalign float32 // out

	_xalign = float32(_arg1)
	_yalign = float32(_arg2)

	return _xalign, _yalign
}

// AlignmentMode: get the alignment mode. The alignment mode describes the
// manner in which the renderer is aligned (see :xalign and :yalign).
//
// The function returns the following values:
//
//    - gutterRendererAlignmentMode: SourceGutterRendererAlignmentMode.
//
func (renderer *GutterRenderer) AlignmentMode() GutterRendererAlignmentMode {
	var _arg0 *C.GtkSourceGutterRenderer             // out
	var _cret C.GtkSourceGutterRendererAlignmentMode // in

	_arg0 = (*C.GtkSourceGutterRenderer)(unsafe.Pointer(renderer.Native()))

	_cret = C.gtk_source_gutter_renderer_get_alignment_mode(_arg0)
	runtime.KeepAlive(renderer)

	var _gutterRendererAlignmentMode GutterRendererAlignmentMode // out

	_gutterRendererAlignmentMode = GutterRendererAlignmentMode(_cret)

	return _gutterRendererAlignmentMode
}

// Background: get the background color of the renderer.
//
// The function returns the following values:
//
//    - color (optional): return value for a RGBA.
//    - ok: TRUE if the background color is set, FALSE otherwise.
//
func (renderer *GutterRenderer) Background() (*gdk.RGBA, bool) {
	var _arg0 *C.GtkSourceGutterRenderer // out
	var _arg1 C.GdkRGBA                  // in
	var _cret C.gboolean                 // in

	_arg0 = (*C.GtkSourceGutterRenderer)(unsafe.Pointer(renderer.Native()))

	_cret = C.gtk_source_gutter_renderer_get_background(_arg0, &_arg1)
	runtime.KeepAlive(renderer)

	var _color *gdk.RGBA // out
	var _ok bool         // out

	_color = (*gdk.RGBA)(gextras.NewStructNative(unsafe.Pointer((&_arg1))))
	if _cret != 0 {
		_ok = true
	}

	return _color, _ok
}

// Padding: get the x-padding and y-padding of the gutter renderer.
//
// The function returns the following values:
//
//    - xpad (optional): return location for the x-padding, or NULL to ignore.
//    - ypad (optional): return location for the y-padding, or NULL to ignore.
//
func (renderer *GutterRenderer) Padding() (xpad int, ypad int) {
	var _arg0 *C.GtkSourceGutterRenderer // out
	var _arg1 C.gint                     // in
	var _arg2 C.gint                     // in

	_arg0 = (*C.GtkSourceGutterRenderer)(unsafe.Pointer(renderer.Native()))

	C.gtk_source_gutter_renderer_get_padding(_arg0, &_arg1, &_arg2)
	runtime.KeepAlive(renderer)

	var _xpad int // out
	var _ypad int // out

	_xpad = int(_arg1)
	_ypad = int(_arg2)

	return _xpad, _ypad
}

// Size: get the size of the renderer.
//
// The function returns the following values:
//
//    - gint: size of the renderer.
//
func (renderer *GutterRenderer) Size() int {
	var _arg0 *C.GtkSourceGutterRenderer // out
	var _cret C.gint                     // in

	_arg0 = (*C.GtkSourceGutterRenderer)(unsafe.Pointer(renderer.Native()))

	_cret = C.gtk_source_gutter_renderer_get_size(_arg0)
	runtime.KeepAlive(renderer)

	var _gint int // out

	_gint = int(_cret)

	return _gint
}

// View: get the view associated to the gutter renderer.
//
// The function returns the following values:
//
//    - textView: TextView.
//
func (renderer *GutterRenderer) View() *gtk.TextView {
	var _arg0 *C.GtkSourceGutterRenderer // out
	var _cret *C.GtkTextView             // in

	_arg0 = (*C.GtkSourceGutterRenderer)(unsafe.Pointer(renderer.Native()))

	_cret = C.gtk_source_gutter_renderer_get_view(_arg0)
	runtime.KeepAlive(renderer)

	var _textView *gtk.TextView // out

	{
		obj := externglib.Take(unsafe.Pointer(_cret))
		_textView = &gtk.TextView{
			Container: gtk.Container{
				Widget: gtk.Widget{
					InitiallyUnowned: externglib.InitiallyUnowned{
						Object: obj,
					},
					Object: obj,
					ImplementorIface: atk.ImplementorIface{
						Object: obj,
					},
					Buildable: gtk.Buildable{
						Object: obj,
					},
				},
			},
			Object: obj,
			Scrollable: gtk.Scrollable{
				Object: obj,
			},
		}
	}

	return _textView
}

// Visible: get whether the gutter renderer is visible.
//
// The function returns the following values:
//
//    - ok: TRUE if the renderer is visible, FALSE otherwise.
//
func (renderer *GutterRenderer) Visible() bool {
	var _arg0 *C.GtkSourceGutterRenderer // out
	var _cret C.gboolean                 // in

	_arg0 = (*C.GtkSourceGutterRenderer)(unsafe.Pointer(renderer.Native()))

	_cret = C.gtk_source_gutter_renderer_get_visible(_arg0)
	runtime.KeepAlive(renderer)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// WindowType: get the TextWindowType associated with the gutter renderer.
//
// The function returns the following values:
//
//    - textWindowType: TextWindowType.
//
func (renderer *GutterRenderer) WindowType() gtk.TextWindowType {
	var _arg0 *C.GtkSourceGutterRenderer // out
	var _cret C.GtkTextWindowType        // in

	_arg0 = (*C.GtkSourceGutterRenderer)(unsafe.Pointer(renderer.Native()))

	_cret = C.gtk_source_gutter_renderer_get_window_type(_arg0)
	runtime.KeepAlive(renderer)

	var _textWindowType gtk.TextWindowType // out

	_textWindowType = gtk.TextWindowType(_cret)

	return _textWindowType
}

// QueryActivatable: get whether the renderer is activatable at the location in
// event. This is called from SourceGutter to determine whether a renderer is
// activatable using the mouse pointer.
//
// The function takes the following parameters:
//
//    - iter at the start of the line to be activated.
//    - area of the cell area to be activated.
//    - event that triggered the query.
//
// The function returns the following values:
//
//    - ok: TRUE if the renderer can be activated, FALSE otherwise.
//
func (renderer *GutterRenderer) QueryActivatable(iter *gtk.TextIter, area *gdk.Rectangle, event *gdk.Event) bool {
	var _arg0 *C.GtkSourceGutterRenderer // out
	var _arg1 *C.GtkTextIter             // out
	var _arg2 *C.GdkRectangle            // out
	var _arg3 *C.GdkEvent                // out
	var _cret C.gboolean                 // in

	_arg0 = (*C.GtkSourceGutterRenderer)(unsafe.Pointer(renderer.Native()))
	_arg1 = (*C.GtkTextIter)(gextras.StructNative(unsafe.Pointer(iter)))
	_arg2 = (*C.GdkRectangle)(gextras.StructNative(unsafe.Pointer(area)))
	_arg3 = (*C.GdkEvent)(gextras.StructNative(unsafe.Pointer(event)))

	_cret = C.gtk_source_gutter_renderer_query_activatable(_arg0, _arg1, _arg2, _arg3)
	runtime.KeepAlive(renderer)
	runtime.KeepAlive(iter)
	runtime.KeepAlive(area)
	runtime.KeepAlive(event)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// QueryData: emit the SourceGutterRenderer::query-data signal. This function is
// called to query for data just before rendering a cell. This is called from
// the SourceGutter. Implementations can override the default signal handler or
// can connect a signal handler externally to the
// SourceGutterRenderer::query-data signal.
//
// The function takes the following parameters:
//
//    - start: TextIter.
//    - end: TextIter.
//    - state: SourceGutterRendererState.
//
func (renderer *GutterRenderer) QueryData(start, end *gtk.TextIter, state GutterRendererState) {
	var _arg0 *C.GtkSourceGutterRenderer     // out
	var _arg1 *C.GtkTextIter                 // out
	var _arg2 *C.GtkTextIter                 // out
	var _arg3 C.GtkSourceGutterRendererState // out

	_arg0 = (*C.GtkSourceGutterRenderer)(unsafe.Pointer(renderer.Native()))
	_arg1 = (*C.GtkTextIter)(gextras.StructNative(unsafe.Pointer(start)))
	_arg2 = (*C.GtkTextIter)(gextras.StructNative(unsafe.Pointer(end)))
	_arg3 = C.GtkSourceGutterRendererState(state)

	C.gtk_source_gutter_renderer_query_data(_arg0, _arg1, _arg2, _arg3)
	runtime.KeepAlive(renderer)
	runtime.KeepAlive(start)
	runtime.KeepAlive(end)
	runtime.KeepAlive(state)
}

// QueryTooltip emits the SourceGutterRenderer::query-tooltip signal. This
// function is called from SourceGutter. Implementations can override the
// default signal handler or can connect to the signal externally.
//
// The function takes the following parameters:
//
//    - iter: TextIter.
//    - area: Rectangle.
//    - x position of the tooltip.
//    - y position of the tooltip.
//    - tooltip: Tooltip.
//
// The function returns the following values:
//
//    - ok: TRUE if the tooltip has been set, FALSE otherwise.
//
func (renderer *GutterRenderer) QueryTooltip(iter *gtk.TextIter, area *gdk.Rectangle, x, y int, tooltip *gtk.Tooltip) bool {
	var _arg0 *C.GtkSourceGutterRenderer // out
	var _arg1 *C.GtkTextIter             // out
	var _arg2 *C.GdkRectangle            // out
	var _arg3 C.gint                     // out
	var _arg4 C.gint                     // out
	var _arg5 *C.GtkTooltip              // out
	var _cret C.gboolean                 // in

	_arg0 = (*C.GtkSourceGutterRenderer)(unsafe.Pointer(renderer.Native()))
	_arg1 = (*C.GtkTextIter)(gextras.StructNative(unsafe.Pointer(iter)))
	_arg2 = (*C.GdkRectangle)(gextras.StructNative(unsafe.Pointer(area)))
	_arg3 = C.gint(x)
	_arg4 = C.gint(y)
	_arg5 = (*C.GtkTooltip)(unsafe.Pointer(tooltip.Native()))

	_cret = C.gtk_source_gutter_renderer_query_tooltip(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5)
	runtime.KeepAlive(renderer)
	runtime.KeepAlive(iter)
	runtime.KeepAlive(area)
	runtime.KeepAlive(x)
	runtime.KeepAlive(y)
	runtime.KeepAlive(tooltip)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// QueueDraw emits the SourceGutterRenderer::queue-draw signal of the renderer.
// Call this from an implementation to inform that the renderer has changed such
// that it needs to redraw.
func (renderer *GutterRenderer) QueueDraw() {
	var _arg0 *C.GtkSourceGutterRenderer // out

	_arg0 = (*C.GtkSourceGutterRenderer)(unsafe.Pointer(renderer.Native()))

	C.gtk_source_gutter_renderer_queue_draw(_arg0)
	runtime.KeepAlive(renderer)
}

// SetAlignment: set the alignment of the gutter renderer. Both xalign and
// yalign can be -1, which means the values will not be changed (this allows
// changing only one of the values).
//
// xalign is the horizontal alignment. Set to 0 for a left alignment. 1 for a
// right alignment. And 0.5 for centering the cells. yalign is the vertical
// alignment. Set to 0 for a top alignment. 1 for a bottom alignment.
//
// The function takes the following parameters:
//
//    - xalign: x-alignment.
//    - yalign: y-alignment.
//
func (renderer *GutterRenderer) SetAlignment(xalign, yalign float32) {
	var _arg0 *C.GtkSourceGutterRenderer // out
	var _arg1 C.gfloat                   // out
	var _arg2 C.gfloat                   // out

	_arg0 = (*C.GtkSourceGutterRenderer)(unsafe.Pointer(renderer.Native()))
	_arg1 = C.gfloat(xalign)
	_arg2 = C.gfloat(yalign)

	C.gtk_source_gutter_renderer_set_alignment(_arg0, _arg1, _arg2)
	runtime.KeepAlive(renderer)
	runtime.KeepAlive(xalign)
	runtime.KeepAlive(yalign)
}

// SetAlignmentMode: set the alignment mode. The alignment mode describes the
// manner in which the renderer is aligned (see :xalign and :yalign).
//
// The function takes the following parameters:
//
//    - mode: SourceGutterRendererAlignmentMode.
//
func (renderer *GutterRenderer) SetAlignmentMode(mode GutterRendererAlignmentMode) {
	var _arg0 *C.GtkSourceGutterRenderer             // out
	var _arg1 C.GtkSourceGutterRendererAlignmentMode // out

	_arg0 = (*C.GtkSourceGutterRenderer)(unsafe.Pointer(renderer.Native()))
	_arg1 = C.GtkSourceGutterRendererAlignmentMode(mode)

	C.gtk_source_gutter_renderer_set_alignment_mode(_arg0, _arg1)
	runtime.KeepAlive(renderer)
	runtime.KeepAlive(mode)
}

// SetBackground: set the background color of the renderer. If color is set to
// NULL, the renderer will not have a background color.
//
// The function takes the following parameters:
//
//    - color (optional) or NULL.
//
func (renderer *GutterRenderer) SetBackground(color *gdk.RGBA) {
	var _arg0 *C.GtkSourceGutterRenderer // out
	var _arg1 *C.GdkRGBA                 // out

	_arg0 = (*C.GtkSourceGutterRenderer)(unsafe.Pointer(renderer.Native()))
	if color != nil {
		_arg1 = (*C.GdkRGBA)(gextras.StructNative(unsafe.Pointer(color)))
	}

	C.gtk_source_gutter_renderer_set_background(_arg0, _arg1)
	runtime.KeepAlive(renderer)
	runtime.KeepAlive(color)
}

// SetPadding: set the padding of the gutter renderer. Both xpad and ypad can be
// -1, which means the values will not be changed (this allows changing only one
// of the values).
//
// xpad is the left and right padding. ypad is the top and bottom padding.
//
// The function takes the following parameters:
//
//    - xpad: x-padding.
//    - ypad: y-padding.
//
func (renderer *GutterRenderer) SetPadding(xpad, ypad int) {
	var _arg0 *C.GtkSourceGutterRenderer // out
	var _arg1 C.gint                     // out
	var _arg2 C.gint                     // out

	_arg0 = (*C.GtkSourceGutterRenderer)(unsafe.Pointer(renderer.Native()))
	_arg1 = C.gint(xpad)
	_arg2 = C.gint(ypad)

	C.gtk_source_gutter_renderer_set_padding(_arg0, _arg1, _arg2)
	runtime.KeepAlive(renderer)
	runtime.KeepAlive(xpad)
	runtime.KeepAlive(ypad)
}

// SetSize sets the size of the renderer. A value of -1 specifies that the size
// is to be determined dynamically.
//
// The function takes the following parameters:
//
//    - size: size.
//
func (renderer *GutterRenderer) SetSize(size int) {
	var _arg0 *C.GtkSourceGutterRenderer // out
	var _arg1 C.gint                     // out

	_arg0 = (*C.GtkSourceGutterRenderer)(unsafe.Pointer(renderer.Native()))
	_arg1 = C.gint(size)

	C.gtk_source_gutter_renderer_set_size(_arg0, _arg1)
	runtime.KeepAlive(renderer)
	runtime.KeepAlive(size)
}

// SetVisible: set whether the gutter renderer is visible.
//
// The function takes the following parameters:
//
//    - visible: visibility.
//
func (renderer *GutterRenderer) SetVisible(visible bool) {
	var _arg0 *C.GtkSourceGutterRenderer // out
	var _arg1 C.gboolean                 // out

	_arg0 = (*C.GtkSourceGutterRenderer)(unsafe.Pointer(renderer.Native()))
	if visible {
		_arg1 = C.TRUE
	}

	C.gtk_source_gutter_renderer_set_visible(_arg0, _arg1)
	runtime.KeepAlive(renderer)
	runtime.KeepAlive(visible)
}
