// Code generated by girgen. DO NOT EDIT.

package gtksource

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/atk"
	externglib "github.com/diamondburned/gotk4/pkg/core/glib"
	"github.com/diamondburned/gotk4/pkg/gtk/v3"
)

// #include <stdlib.h>
// #include <glib-object.h>
// #include <gtksourceview/gtksource.h>
import "C"

// glib.Type values for gtksourcestyleschemechooserwidget.go.
var GTypeStyleSchemeChooserWidget = externglib.Type(C.gtk_source_style_scheme_chooser_widget_get_type())

func init() {
	externglib.RegisterGValueMarshalers([]externglib.TypeMarshaler{
		{T: GTypeStyleSchemeChooserWidget, F: marshalStyleSchemeChooserWidget},
	})
}

// StyleSchemeChooserWidgetOverrider contains methods that are overridable.
type StyleSchemeChooserWidgetOverrider interface {
}

type StyleSchemeChooserWidget struct {
	_ [0]func() // equal guard
	gtk.Bin

	*externglib.Object
	StyleSchemeChooser
}

var (
	_ gtk.Binner          = (*StyleSchemeChooserWidget)(nil)
	_ externglib.Objector = (*StyleSchemeChooserWidget)(nil)
)

func classInitStyleSchemeChooserWidgetter(gclassPtr, data C.gpointer) {
	C.g_type_class_add_private(gclassPtr, C.gsize(unsafe.Sizeof(uintptr(0))))

	goffset := C.g_type_class_get_instance_private_offset(gclassPtr)
	*(*C.gpointer)(unsafe.Add(unsafe.Pointer(gclassPtr), goffset)) = data

}

func wrapStyleSchemeChooserWidget(obj *externglib.Object) *StyleSchemeChooserWidget {
	return &StyleSchemeChooserWidget{
		Bin: gtk.Bin{
			Container: gtk.Container{
				Widget: gtk.Widget{
					InitiallyUnowned: externglib.InitiallyUnowned{
						Object: obj,
					},
					Object: obj,
					ImplementorIface: atk.ImplementorIface{
						Object: obj,
					},
					Buildable: gtk.Buildable{
						Object: obj,
					},
				},
			},
		},
		Object: obj,
		StyleSchemeChooser: StyleSchemeChooser{
			Object: obj,
		},
	}
}

func marshalStyleSchemeChooserWidget(p uintptr) (interface{}, error) {
	return wrapStyleSchemeChooserWidget(externglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// NewStyleSchemeChooserWidget creates a new SourceStyleSchemeChooserWidget.
//
// The function returns the following values:
//
//    - styleSchemeChooserWidget: new SourceStyleSchemeChooserWidget.
//
func NewStyleSchemeChooserWidget() *StyleSchemeChooserWidget {
	var _cret *C.GtkWidget // in

	_cret = C.gtk_source_style_scheme_chooser_widget_new()

	var _styleSchemeChooserWidget *StyleSchemeChooserWidget // out

	_styleSchemeChooserWidget = wrapStyleSchemeChooserWidget(externglib.Take(unsafe.Pointer(_cret)))

	return _styleSchemeChooserWidget
}
