// Code generated by girgen. DO NOT EDIT.

package gtksource

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/atk"
	externglib "github.com/diamondburned/gotk4/pkg/core/glib"
	"github.com/diamondburned/gotk4/pkg/gtk/v3"
)

// #include <stdlib.h>
// #include <glib-object.h>
// #include <gtksourceview/gtksource.h>
import "C"

// glib.Type values for gtksourcestyleschemechooserbutton.go.
var GTypeStyleSchemeChooserButton = externglib.Type(C.gtk_source_style_scheme_chooser_button_get_type())

func init() {
	externglib.RegisterGValueMarshalers([]externglib.TypeMarshaler{
		{T: GTypeStyleSchemeChooserButton, F: marshalStyleSchemeChooserButton},
	})
}

// StyleSchemeChooserButtonOverrider contains methods that are overridable.
type StyleSchemeChooserButtonOverrider interface {
}

type StyleSchemeChooserButton struct {
	_ [0]func() // equal guard
	gtk.Button

	*externglib.Object
	StyleSchemeChooser
}

var (
	_ externglib.Objector = (*StyleSchemeChooserButton)(nil)
	_ gtk.Binner          = (*StyleSchemeChooserButton)(nil)
)

func classInitStyleSchemeChooserButtonner(gclassPtr, data C.gpointer) {
	C.g_type_class_add_private(gclassPtr, C.gsize(unsafe.Sizeof(uintptr(0))))

	goffset := C.g_type_class_get_instance_private_offset(gclassPtr)
	*(*C.gpointer)(unsafe.Add(unsafe.Pointer(gclassPtr), goffset)) = data

}

func wrapStyleSchemeChooserButton(obj *externglib.Object) *StyleSchemeChooserButton {
	return &StyleSchemeChooserButton{
		Button: gtk.Button{
			Bin: gtk.Bin{
				Container: gtk.Container{
					Widget: gtk.Widget{
						InitiallyUnowned: externglib.InitiallyUnowned{
							Object: obj,
						},
						Object: obj,
						ImplementorIface: atk.ImplementorIface{
							Object: obj,
						},
						Buildable: gtk.Buildable{
							Object: obj,
						},
					},
				},
			},
			Object: obj,
			Actionable: gtk.Actionable{
				Widget: gtk.Widget{
					InitiallyUnowned: externglib.InitiallyUnowned{
						Object: obj,
					},
					Object: obj,
					ImplementorIface: atk.ImplementorIface{
						Object: obj,
					},
					Buildable: gtk.Buildable{
						Object: obj,
					},
				},
			},
			Activatable: gtk.Activatable{
				Object: obj,
			},
		},
		Object: obj,
		StyleSchemeChooser: StyleSchemeChooser{
			Object: obj,
		},
	}
}

func marshalStyleSchemeChooserButton(p uintptr) (interface{}, error) {
	return wrapStyleSchemeChooserButton(externglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// NewStyleSchemeChooserButton creates a new SourceStyleSchemeChooserButton.
//
// The function returns the following values:
//
//    - styleSchemeChooserButton: new SourceStyleSchemeChooserButton.
//
func NewStyleSchemeChooserButton() *StyleSchemeChooserButton {
	var _cret *C.GtkWidget // in

	_cret = C.gtk_source_style_scheme_chooser_button_new()

	var _styleSchemeChooserButton *StyleSchemeChooserButton // out

	_styleSchemeChooserButton = wrapStyleSchemeChooserButton(externglib.Take(unsafe.Pointer(_cret)))

	return _styleSchemeChooserButton
}
