// Code generated by girgen. DO NOT EDIT.

package gtksource

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/atk"
	"github.com/diamondburned/gotk4/pkg/core/gbox"
	"github.com/diamondburned/gotk4/pkg/core/gextras"
	externglib "github.com/diamondburned/gotk4/pkg/core/glib"
	"github.com/diamondburned/gotk4/pkg/gtk/v3"
)

// #include <stdlib.h>
// #include <glib-object.h>
// #include <gtksourceview/gtksource.h>
// extern void _gotk4_gtksource3_CompletionInfoClass_before_show(GtkSourceCompletionInfo*);
// extern void _gotk4_gtksource3_CompletionInfo_ConnectBeforeShow(gpointer, guintptr);
import "C"

// glib.Type values for gtksourcecompletioninfo.go.
var GTypeCompletionInfo = externglib.Type(C.gtk_source_completion_info_get_type())

func init() {
	externglib.RegisterGValueMarshalers([]externglib.TypeMarshaler{
		{T: GTypeCompletionInfo, F: marshalCompletionInfo},
	})
}

// CompletionInfoOverrider contains methods that are overridable.
type CompletionInfoOverrider interface {
	BeforeShow()
}

type CompletionInfo struct {
	_ [0]func() // equal guard
	gtk.Window
}

var (
	_ gtk.Binner = (*CompletionInfo)(nil)
)

func classInitCompletionInfor(gclassPtr, data C.gpointer) {
	C.g_type_class_add_private(gclassPtr, C.gsize(unsafe.Sizeof(uintptr(0))))

	goffset := C.g_type_class_get_instance_private_offset(gclassPtr)
	*(*C.gpointer)(unsafe.Add(unsafe.Pointer(gclassPtr), goffset)) = data

	goval := gbox.Get(uintptr(data))
	pclass := (*C.GtkSourceCompletionInfoClass)(unsafe.Pointer(gclassPtr))
	// gclass := (*C.GTypeClass)(unsafe.Pointer(gclassPtr))
	// pclass := (*C.GtkSourceCompletionInfoClass)(unsafe.Pointer(C.g_type_class_peek_parent(gclass)))

	if _, ok := goval.(interface{ BeforeShow() }); ok {
		pclass.before_show = (*[0]byte)(C._gotk4_gtksource3_CompletionInfoClass_before_show)
	}
}

//export _gotk4_gtksource3_CompletionInfoClass_before_show
func _gotk4_gtksource3_CompletionInfoClass_before_show(arg0 *C.GtkSourceCompletionInfo) {
	goval := externglib.GoPrivateFromObject(unsafe.Pointer(arg0))
	iface := goval.(interface{ BeforeShow() })

	iface.BeforeShow()
}

func wrapCompletionInfo(obj *externglib.Object) *CompletionInfo {
	return &CompletionInfo{
		Window: gtk.Window{
			Bin: gtk.Bin{
				Container: gtk.Container{
					Widget: gtk.Widget{
						InitiallyUnowned: externglib.InitiallyUnowned{
							Object: obj,
						},
						Object: obj,
						ImplementorIface: atk.ImplementorIface{
							Object: obj,
						},
						Buildable: gtk.Buildable{
							Object: obj,
						},
					},
				},
			},
		},
	}
}

func marshalCompletionInfo(p uintptr) (interface{}, error) {
	return wrapCompletionInfo(externglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

//export _gotk4_gtksource3_CompletionInfo_ConnectBeforeShow
func _gotk4_gtksource3_CompletionInfo_ConnectBeforeShow(arg0 C.gpointer, arg1 C.guintptr) {
	var f func()
	{
		closure := externglib.ConnectedGeneratedClosure(uintptr(arg1))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func())
	}

	f()
}

// ConnectBeforeShow: this signal is emitted before any "show" management. You
// can connect to this signal if you want to change some properties or position
// before the real "show".
func (info *CompletionInfo) ConnectBeforeShow(f func()) externglib.SignalHandle {
	return externglib.ConnectGeneratedClosure(info, "before-show", false, unsafe.Pointer(C._gotk4_gtksource3_CompletionInfo_ConnectBeforeShow), f)
}

// The function returns the following values:
//
//    - completionInfo: new GtkSourceCompletionInfo.
//
func NewCompletionInfo() *CompletionInfo {
	var _cret *C.GtkSourceCompletionInfo // in

	_cret = C.gtk_source_completion_info_new()

	var _completionInfo *CompletionInfo // out

	_completionInfo = wrapCompletionInfo(externglib.Take(unsafe.Pointer(_cret)))

	return _completionInfo
}

// Widget: get the current content widget.
//
// Deprecated: Use gtk_bin_get_child() instead.
//
// The function returns the following values:
//
//    - widget: current content widget.
//
func (info *CompletionInfo) Widget() gtk.Widgetter {
	var _arg0 *C.GtkSourceCompletionInfo // out
	var _cret *C.GtkWidget               // in

	_arg0 = (*C.GtkSourceCompletionInfo)(unsafe.Pointer(externglib.InternObject(info).Native()))

	_cret = C.gtk_source_completion_info_get_widget(_arg0)
	runtime.KeepAlive(info)

	var _widget gtk.Widgetter // out

	{
		objptr := unsafe.Pointer(_cret)
		if objptr == nil {
			panic("object of type gtk.Widgetter is nil")
		}

		object := externglib.Take(objptr)
		casted := object.WalkCast(func(obj externglib.Objector) bool {
			_, ok := obj.(gtk.Widgetter)
			return ok
		})
		rv, ok := casted.(gtk.Widgetter)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching gtk.Widgetter")
		}
		_widget = rv
	}

	return _widget
}

// MoveToIter moves the SourceCompletionInfo to iter. If iter is NULL info is
// moved to the cursor position. Moving will respect the Gravity setting of the
// info window and will ensure the line at iter is not occluded by the window.
//
// The function takes the following parameters:
//
//    - view on which the info window should be positioned.
//    - iter (optional): TextIter.
//
func (info *CompletionInfo) MoveToIter(view *gtk.TextView, iter *gtk.TextIter) {
	var _arg0 *C.GtkSourceCompletionInfo // out
	var _arg1 *C.GtkTextView             // out
	var _arg2 *C.GtkTextIter             // out

	_arg0 = (*C.GtkSourceCompletionInfo)(unsafe.Pointer(externglib.InternObject(info).Native()))
	_arg1 = (*C.GtkTextView)(unsafe.Pointer(externglib.InternObject(view).Native()))
	if iter != nil {
		_arg2 = (*C.GtkTextIter)(gextras.StructNative(unsafe.Pointer(iter)))
	}

	C.gtk_source_completion_info_move_to_iter(_arg0, _arg1, _arg2)
	runtime.KeepAlive(info)
	runtime.KeepAlive(view)
	runtime.KeepAlive(iter)
}

// SetWidget sets the content widget of the info window. See that the previous
// widget will lose a reference and it can be destroyed, so if you do not want
// this to happen you must use g_object_ref() before calling this method.
//
// Deprecated: Use gtk_container_add() instead. If there is already a child
// widget, remove it with gtk_container_remove().
//
// The function takes the following parameters:
//
//    - widget (optional): Widget.
//
func (info *CompletionInfo) SetWidget(widget gtk.Widgetter) {
	var _arg0 *C.GtkSourceCompletionInfo // out
	var _arg1 *C.GtkWidget               // out

	_arg0 = (*C.GtkSourceCompletionInfo)(unsafe.Pointer(externglib.InternObject(info).Native()))
	if widget != nil {
		_arg1 = (*C.GtkWidget)(unsafe.Pointer(externglib.InternObject(widget).Native()))
	}

	C.gtk_source_completion_info_set_widget(_arg0, _arg1)
	runtime.KeepAlive(info)
	runtime.KeepAlive(widget)
}
